# Generated by Django 5.1.6 on 2025-02-24 08:50

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBoutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='GestionBoutique.produit'),
        ),
    ]
