# Generated by Django 5.1.6 on 2025-02-26 09:38

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBoutique', '0003_categorie_image_alter_vente_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='default_images/'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='GestionBoutique.produit'),
        ),
    ]
